2025-06-24 12:52:01,971 ERROR: Exception on /api/analyze [POST] [in /Users/aryan/opt/anaconda3/lib/python3.8/site-packages/flask/app.py:828]
Traceback (most recent call last):
  File "/Users/aryan/opt/anaconda3/lib/python3.8/site-packages/flask/app.py", line 1463, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/aryan/opt/anaconda3/lib/python3.8/site-packages/flask/app.py", line 872, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/aryan/opt/anaconda3/lib/python3.8/site-packages/flask/app.py", line 870, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/aryan/opt/anaconda3/lib/python3.8/site-packages/flask/app.py", line 855, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "/Users/aryan/opt/anaconda3/lib/python3.8/site-packages/flask_login/utils.py", line 290, in decorated_view
    return current_app.ensure_sync(func)(*args, **kwargs)
  File "/Users/aryan/Documents/GitHub/job-bot-/app/routes.py", line 197, in analyze
    analysis = analyze_job_description(data['job_description'], resume.content)
  File "/Users/aryan/Documents/GitHub/job-bot-/app/ai_utils.py", line 51, in analyze_job_description
    Extract a list of required skills and qualifications from this job description:
  File "/Users/aryan/Documents/GitHub/job-bot-/app/ai_utils.py", line 23, in call_lmstudio
    if "choices" in result and result["choices"]:
KeyError: 'choices'
2025-06-24 12:56:01,891 INFO: Job Bot startup [in /Users/aryan/Documents/GitHub/job-bot-/app/__init__.py:53]
2025-06-24 12:56:04,230 INFO: Database tables created successfully [in /Users/aryan/Documents/GitHub/job-bot-/app/__init__.py:59]
2025-06-24 12:56:12,580 ERROR: Exception on /api/analyze [POST] [in /Users/aryan/opt/anaconda3/lib/python3.8/site-packages/flask/app.py:828]
Traceback (most recent call last):
  File "/Users/aryan/opt/anaconda3/lib/python3.8/site-packages/flask/app.py", line 1463, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/aryan/opt/anaconda3/lib/python3.8/site-packages/flask/app.py", line 872, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/aryan/opt/anaconda3/lib/python3.8/site-packages/flask/app.py", line 870, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/aryan/opt/anaconda3/lib/python3.8/site-packages/flask/app.py", line 855, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "/Users/aryan/opt/anaconda3/lib/python3.8/site-packages/flask_login/utils.py", line 290, in decorated_view
    return current_app.ensure_sync(func)(*args, **kwargs)
  File "/Users/aryan/Documents/GitHub/job-bot-/app/routes.py", line 197, in analyze
    analysis = analyze_job_description(data['job_description'], resume.content)
  File "/Users/aryan/Documents/GitHub/job-bot-/app/ai_utils.py", line 58, in analyze_job_description
    job_skills = [skill.strip() for skill in job_skills_str.split(',')]
AttributeError: 'NoneType' object has no attribute 'split'
2025-06-24 12:56:22,490 ERROR: Exception on /api/analyze [POST] [in /Users/aryan/opt/anaconda3/lib/python3.8/site-packages/flask/app.py:828]
Traceback (most recent call last):
  File "/Users/aryan/opt/anaconda3/lib/python3.8/site-packages/flask/app.py", line 1463, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/aryan/opt/anaconda3/lib/python3.8/site-packages/flask/app.py", line 872, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/aryan/opt/anaconda3/lib/python3.8/site-packages/flask/app.py", line 870, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/aryan/opt/anaconda3/lib/python3.8/site-packages/flask/app.py", line 855, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "/Users/aryan/opt/anaconda3/lib/python3.8/site-packages/flask_login/utils.py", line 290, in decorated_view
    return current_app.ensure_sync(func)(*args, **kwargs)
  File "/Users/aryan/Documents/GitHub/job-bot-/app/routes.py", line 197, in analyze
    analysis = analyze_job_description(data['job_description'], resume.content)
  File "/Users/aryan/Documents/GitHub/job-bot-/app/ai_utils.py", line 58, in analyze_job_description
    job_skills = [skill.strip() for skill in job_skills_str.split(',')]
AttributeError: 'NoneType' object has no attribute 'split'
2025-06-24 12:58:57,817 ERROR: Exception on /api/analyze [POST] [in /Users/aryan/opt/anaconda3/lib/python3.8/site-packages/flask/app.py:828]
Traceback (most recent call last):
  File "/Users/aryan/opt/anaconda3/lib/python3.8/site-packages/flask/app.py", line 1463, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/aryan/opt/anaconda3/lib/python3.8/site-packages/flask/app.py", line 872, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/aryan/opt/anaconda3/lib/python3.8/site-packages/flask/app.py", line 870, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/aryan/opt/anaconda3/lib/python3.8/site-packages/flask/app.py", line 855, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "/Users/aryan/opt/anaconda3/lib/python3.8/site-packages/flask_login/utils.py", line 290, in decorated_view
    return current_app.ensure_sync(func)(*args, **kwargs)
  File "/Users/aryan/Documents/GitHub/job-bot-/app/routes.py", line 197, in analyze
    analysis = analyze_job_description(data['job_description'], resume.content)
  File "/Users/aryan/Documents/GitHub/job-bot-/app/ai_utils.py", line 58, in analyze_job_description
    job_skills = [skill.strip() for skill in job_skills_str.split(',')]
AttributeError: 'NoneType' object has no attribute 'split'
2025-06-24 13:00:42,320 INFO: Job Bot startup [in /Users/aryan/Documents/GitHub/job-bot-/app/__init__.py:53]
2025-06-24 13:00:44,706 INFO: Database tables created successfully [in /Users/aryan/Documents/GitHub/job-bot-/app/__init__.py:59]
2025-06-24 13:02:40,127 ERROR: Exception on /api/generate-cover-letter [POST] [in /Users/aryan/opt/anaconda3/lib/python3.8/site-packages/flask/app.py:828]
Traceback (most recent call last):
  File "/Users/aryan/opt/anaconda3/lib/python3.8/site-packages/flask/app.py", line 1463, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/aryan/opt/anaconda3/lib/python3.8/site-packages/flask/app.py", line 872, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/aryan/opt/anaconda3/lib/python3.8/site-packages/flask/app.py", line 870, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/aryan/opt/anaconda3/lib/python3.8/site-packages/flask/app.py", line 855, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "/Users/aryan/opt/anaconda3/lib/python3.8/site-packages/flask_login/utils.py", line 290, in decorated_view
    return current_app.ensure_sync(func)(*args, **kwargs)
  File "/Users/aryan/Documents/GitHub/job-bot-/app/routes.py", line 212, in generate_cover_letter_api
    cover_letter = generate_cover_letter(data['job_description'], resume.content)
  File "/Users/aryan/opt/anaconda3/lib/python3.8/site-packages/flask_login/utils.py", line 290, in decorated_view
    return current_app.ensure_sync(func)(*args, **kwargs)
TypeError: generate_cover_letter() takes 0 positional arguments but 2 were given
2025-06-24 13:02:52,300 ERROR: Exception on /api/generate-cover-letter [POST] [in /Users/aryan/opt/anaconda3/lib/python3.8/site-packages/flask/app.py:828]
Traceback (most recent call last):
  File "/Users/aryan/opt/anaconda3/lib/python3.8/site-packages/flask/app.py", line 1463, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/aryan/opt/anaconda3/lib/python3.8/site-packages/flask/app.py", line 872, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/aryan/opt/anaconda3/lib/python3.8/site-packages/flask/app.py", line 870, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/aryan/opt/anaconda3/lib/python3.8/site-packages/flask/app.py", line 855, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "/Users/aryan/opt/anaconda3/lib/python3.8/site-packages/flask_login/utils.py", line 290, in decorated_view
    return current_app.ensure_sync(func)(*args, **kwargs)
  File "/Users/aryan/Documents/GitHub/job-bot-/app/routes.py", line 212, in generate_cover_letter_api
    cover_letter = generate_cover_letter(data['job_description'], resume.content)
  File "/Users/aryan/opt/anaconda3/lib/python3.8/site-packages/flask_login/utils.py", line 290, in decorated_view
    return current_app.ensure_sync(func)(*args, **kwargs)
TypeError: generate_cover_letter() takes 0 positional arguments but 2 were given
